测试

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,52 +1,44 @@
-name: test
+name: Code Quality Check
 
-# Controls when the action will run. Triggers the workflow on push or pull request
-# events but only for the master branch
 on:
   push:
     branches:
       - master
       - develop
-  pull_request:
-    branches:
-      - master
-      - develop
 
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  # This workflow contains a single job called "build"
-  build:
-    # The type of runner that the job will run on
+  check:
     runs-on: ubuntu-latest
 
-    # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
-      # Checkout source code
       - uses: actions/checkout@v2
-      # Cache maven .m2 directory
-      - uses: actions/cache@v2
+
+      # Install dependencies
+      - name: Setup Maven
+        uses: actions/setup-java@v1
+        with:
+          java-version: 11
+      - name: Cache Maven packages
+        uses: actions/cache@v2.1.4
         with:
           path: ~/.m2/repository
           key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
           restore-keys: |
             ${{ runner.os }}-maven-
-      # Install Java 1.8
-      - uses: actions/setup-java@v1
-        with:
-          server-id: alimaven
-          java-version: 11
-      # Code review with Checkstyle
+
+      # Code Format Check with Checkstyle
       - name: Checkstyle
-          run: |
-            mvn checkstyle:checkstyle || true
-            checkstyle_report_path=$(find target/site -name "checkstyle-result.xml")
-            if [ -f "$checkstyle_report_path" ]; then
-              echo "Checkstyle report: $checkstyle_report_path"
-              echo "::error :: Checkstyle found issues in your code. Please fix them before continuing."
-              exit 1
-            fi
-      # Code testing with JUnit
-      - name: JUnit
+        run: |
+          mvn checkstyle:checkstyle
+          checkstyle_report_path=$(find target/site -name "checkstyle-result.xml")
+          if [ -f "$checkstyle_report_path" ]; then
+            echo "Checkstyle report: $checkstyle_report_path"
+            echo "::error :: Checkstyle found issues in your code. Please fix them before continuing."
+            exit 1
+          fi
+
+      # Unit Test with JUnit
+      - name: JUnit Test
         run: |
           mvn test
           test_report_path=$(find target/surefire-reports -name "TEST-*.xml")
@@ -54,13 +46,7 @@ jobs:
             echo "Test report: $test_report_path"
             junit_report=$(cat "$test_report_path")
             echo "::set-output name=junit_report::$junit_report"
+          else
+            echo "::error ::No test report found. Please fix the failed test(s) before continuing."
+            exit 1
           fi
-      # Publish to Apache Maven Central
-      #- run: mvn install:install-file "-Dfile=cobra.jar" "-DgroupId=com.cobra" "-DartifactId=cobra" "-Dversion=0.98.4" "-Dpackaging=jar" "-DgeneratePom=true"
-      #- run: mvn clean compile
-      - run: mvn --batch-mode --update-snapshots verify
-      - run: mkdir staging && cp target/*.jar staging
-      - uses: actions/upload-artifact@v3
-        with:
-          name: Package
-          path: staging
